config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :expenses

  root 'welcome#index'

end

app/models/expense.rb
class Expense < ActiveRecord::Base
	before_save { self.forwhat = forwhat.downcase }

	belongs_to :user


	has_many :uploads

end

app/models/upload.rb
class Upload < ActiveRecord::Base

	belongs_to :expense

	mount_uploader :name, FileUploader



end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :expenses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController


	 skip_before_action :verify_authenticity_token

	def index

				@expenses = Expense.all
	end

	def create

		

		@expense  = current_user.expenses.new(purpose: "Travel", amount: 1289, forwhat: "IT")

		

    if params[:file]

				uploaded_io = params[:file]
	  		File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
	      file.write(uploaded_io.read)

	      @file = @expense.uploads.new(name: uploaded_io.original_filename)

	      @file.save
	  		end

	  end



		
		if @expense.save 

			flash[:success] = "Successfully added new expense..."

			redirect_to root_path

		else
			flash[:danger] = "Failed to add expense. Try again."
			redirect_to root_path
		end

	end



	def new


	end

	def edit
	end

	def show



	end

	def update
	end

	private

	def expense_params

		params.permit(:purpose, :forwhat,:name, :amount, :date, :time)

	end
	
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/expenses/index.html.erb
<h1>Showing all expenses</h1>

<table style="width:90%; align:center">

	
<% @expenses.each do | expense | %> 

<tr>

<td><%= expense.purpose %></td>

<td><%= expense.amount %></td>

<td><%= expense.forwhat %></td>

<td><%= expense.date %></td>

<td><%= expense.time %></td>

<td><%= expense.user_id %></td>

<td><%= expense.uploads</td>

	</tr>

	
<% end %>

</table>


<br><br><br>

<%= link_to "Back to adding new expense", root_url %>


<br><br>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>   

app/views/expenses/new.html.erb
<article>

<section>


     <%= form_tag({action: :create}, multipart: true , :class => 'form-vertical') do %>


 		  Purpose:<br>

      <input id="purpose_travel" name="purpose" type="radio" value="Travel" />
      <label for="purpose_travel">Travel</label><br>
      <input id="purpose_expense_owner" name="purpose" type="radio" value="Expense on behalf of owner" />
      <label for="purpose_expense_owner">Expense on behalf of owner</label><br>
      <input id="purpose_agreement" name="purpose" type="radio" value="agreement(stampduty/printing)" />
      <label for="purpose_agreement">Agreement(stampduty/printing)</label><br>
      <input id="purpose_referral" name="purpose" type="radio" value="referral" />
      <label for="purpose_referral">Referral Bonus</label><br>
      <input id="purpose_it" name="purpose" type="radio" value="IT" />
      <label for="purpose_it">IT</label><br><br>


  Amount: <input type="number" name="amount"><br>

  For what: <input type="text" name="forwhat"><br>

        </select><br><br>

        Date:
<!-- 
        <input type="date" name="date"><br><br>


        Time:

        <input type="time" name="time"><br><br> -->

     
            <%= file_field_tag 'file' %>
         

          <br><br>



      <button type="submit">Submit</button>

       <% end %>

 	</form>

  <p>
  <%= flash[:success] unless flash[:success].blank? %>
  <%= flash[:error] unless flash[:error].blank? %>
</p>



</section>
</article>

<br><br><br>

<a href="/show">Click to view all the expenses</a>

 	
</div>

<script type="text/javascript">

// test on mobile
$('head').append('<meta name="viewport" content="width=device-width, initial-scale=1" />');

// bootstrap-select
$('select').selectpicker({
  mobile: false
});

// inpu mtasking
$('.mask-date').mask("00/00/0000", {
  placeholder: "__-__-____"
});
$('.mask-money').mask('000.000.000.000.000,00', {
  reverse: true
});

// custom checkbox and radio
$('input').iCheck({
  checkboxClass: 'icheckbox_square-blue',
  radioClass: 'iradio_square-blue'
});

</script>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Homestayz</a>
    </div>
    <ul class="nav navbar-nav">
      <li><%= link_to 'Home', root_url %></li>
      <li>  <%= link_to 'New Expense', new_expense_path %> </li>
      <li> <%= link_to 'Show Expenses', expenses_path %></li> 

    </ul>

    <ul class="nav navbar-nav navbar-right">

      <li>       <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>  </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Expenses</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render 'layouts/header' %>

<%= yield %>



   <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>


</body>
</html>

app/views/welcome/index.html.erb
hello